---
abstract: 'Open a file for shared reading and/or writing'
author:
  - 'Steve Hay <shay@cpan.org>'
build_requires:
  Config: '0'
  Errno: '0'
  ExtUtils::MakeMaker: '0'
  FileHandle: '0'
  IO::File: '0'
  IO::Handle: '0'
  Symbol: '0'
  Test::More: '0'
  Win32::WinError: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  Config: '0'
  ExtUtils::MakeMaker: '6.66'
  File::Copy: '0'
  File::Spec::Functions: '0'
  strict: '0'
  warnings: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.96, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-SharedFileOpen
no_index:
  directory:
    - t
    - inc
  package:
    - Win32::SharedFileOpen::_NaturalNumber
requires:
  Errno: '0'
  Exporter: '0'
  Symbol: '0'
  Win32::WinError: '0'
  XSLoader: '0'
  perl: '5.008001'
resources:
  repository: git://github.com/steve-m-hay/Win32-SharedFileOpen.git
version: '4.00'
