---
abstract: 'Open a file for shared reading and/or writing'
author:
  - 'Steve Hay <shay@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Win32-SharedFileOpen
no_index:
  directory:
    - inc
    - t
requires:
  Win32::WinError: 0
  perl: 5.6.0
version: 3.38
