name: Win32-SharedFileOpen
version: 3.31
abstract: Open a file for shared reading and/or writing
author: Steve Hay <shay@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  Win32::WinError: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
